export type AudioPageData = {
  AudioImg1: string;
  AudioImg2: string;
  AudioImg3: string;
  AudioInfo1: string;
  AudioInfo2: string;
  AudioInfo3A: string;
  AudioInfo3B: string;
  AudioInfo4: string;
  AudioSlideTitle: string;
  AudioTitle1: string;
  AudioTitle2: string;
  AudioTitle3: string;
  AudioTitle4: string;
  DocumentID: string;
  audioDetails: string[];
  audioImages: string[];
  id: string;
  label: string;
};
