export type ServicePageData = {
  id: string;
  label: string;
  AutoImg: string;
  AudioImg: string;
  AutoInfo: string;
  VideoImg: string;
  PhoneImg: string;
  SplashImg: string;
  AudioInfo: string;
  AutoTitle: string;
  VideoInfo: string;
  PhoneInfo: string;
  DocumentID: string;
  AudioTitle: string;
  VideoTitle: string;
  PhoneTitle: string;
  SplashTitle: string;
  SecurityImg: string;
  SecurityInfo: string;
  ServicesTitle: string;
  SecurityTitle: string;
  SplashSubTitle: string;
  ServicesSubtitle: string;
};
