export type ServicePageData = {
  'id': string;
  'label': string;
  'DocumentID': string;
  'SplashImg': string;
  'SplashSubTitle': string;
  'SplashTitle': string;
  'ServicesTitle': string;
  'ServicesSubtitle': string;
  'AudioImg': string;
  'AudioTitle': string;
  'AudioInfo': string;
  'AutoImg': string;
  'AutoTitle': string;
  'AutoInfo': string;
  'VideoImg': string;
  'VideoTitle': string;
  'VideoInfo': string;
  'PhoneImg': string;
  'PhoneTitle': string;
  'PhoneInfo': string;
  'SecurityImg': string;
  'SecurityTitle': string;
  'SecurityInfo': string;
};
