export type VideoPageData = {
  id: string;
  label: string;
  VidImg1: string;
  VidImg2: string;
  VidImg3: string;
  VidInfo1: string;
  VidInfo2: string;
  VidInfo3A: string;
  VidInfo3B: string;
  VidInfo4A: string;
  VidInfo4B: string;
  VidTitle1: string;
  VidTitle2: string;
  VidTitle3: string;
  VidTitle4: string;
  DocumentID: string;
  VideoIcons: string[];
  VideoLinks: string[];
  VideoNames: string[];
  VidSlideTitle: string;
  VideoImages: string[];
};
